project:
  type: website


website:
  sidebar: false
  title: "Marianna Rosso"
  navbar:
    left:
      - href: index.qmd
        text: Welcome
      - href: Projects.qmd
        text: CV
      - href: Graphics.qmd
        text: Graphics
      - href: Publications.qmd
        text: Publications

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual

