project:
  type: website


website:
  sidebar:
    style: "docked"
    search: false
    contents:
      - href: index.qmd#welcome
        text: Welcome
      - href: index.qmd#research
        text: Research
      - href: index.qmd#cv
        text: Short CV
      - href: index.qmd#projects
        text: Projects
      - href: index.qmd#publications
        text: Publications
      - href: index.qmd#cake
        text: Sweets
        
        
format:
  html:
    link-external-newwindow: true
    theme: journal
    css: styles.css
    toc: true
    include-in-header: head.html

editor: visual

