project:
  type: website


website:
  sidebar: false
  title: "Marianna Rosso"
  navbar:
    left:
      - href: index.qmd
        text: Welcome
      - href: DataViz.qmd
        text: DataViz
      - href: Graphics.qmd
        text: Graphics
      - href: Publications.qmd
        text: Publications
      - href: Projects.qmd
        text: Projects

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

