---
toc: false
format: html
css: styles.css
---

<footer>Please note: this page is still under construction.</footer>


<style>
  body {
    background-color: #eb6864;
  }
</style>

<style>
  @import url('https://fonts.googleapis.com/css2?family=Archivo+Narrow:wght@400;700&display=swap');
  @import url('https://fonts.googleapis.com/css2?family=Great+Vibes:wght@400;700&display=swap');
  @import url('https://fonts.googleapis.com/css2?family=Crimson+Pro:wght@200;700&display=swap');
</style> 

<div class="vertical-line" style="border-left: 2px solid #fff6f5; height: 100vh; position: fixed; left: 300px; top: 0;"></div>


<!-- Curved arrow -->
<svg width="400" height="400" style="position: absolute; top: 105px; left: 120px;">
  <!-- Path for curved arrow -->
  <path d="M 4 1 C 25 27 92 1 88 32 C 74 61 30 14 74 7 C 99 4 121 69 160 50 M 160 50 L 154.8 57.3 M 160 50 L 152 47"  
        stroke="#fcb1aa" stroke-width="1" fill="none" />
</svg>

<div style="position: absolute; top: 85px; left: 70px; font-size: 15px; color: #ffd3cf;font-family: 'Great Vibes', sans-serif;">
  <p>Click for more info!</p>
</div>

<!-- Entry1: CRS postdoc-->
<!-- Circle-->
<div class="hover-circle" style="position: absolute; top: 145px; left: 292px; width: 18px; height: 18px; border: 2px solid #fff6f5; border-radius: 50%;" onclick="toggleInfo('info1')"></div>

<!-- Hover Text box -->
<div id="info1" style="position: absolute; top: 170px; left: 80px; width: 200px; padding: 10px; background-color: rgba(255, 255, 255, 0.9); color: #333; font-size: 16px; font-family: 'Crimson Pro', sans-serif; border: 1px solid #fff6f5; border-radius: 5px; display: none;">
  <p>I focus on facilitating and implementing evidence synthesis for researchers in animal studies as a 3Rs instrument. Additionally, I am dedicated to disseminating my work and training young researchers in alternative methods for animal experimentation. More info <a href="https://stride-lab.pages.uzh.ch/website/people/rosso-marianna/" target="_blank">here</a></p>
</div>

<!-- Text -->
<div style="position: absolute; top: 138px; left: 330px; color: white;line-height: 1.1;">
  <p style="margin: 0; font-family: 'Archivo Narrow', sans-serif;font-size: 24px; ">2022 - current</p>
  <p style="margin: 0; font-family: 'Crimson Pro', serif;font-size: 19px; ">Post Doctoral Researcher at the STRIDE-Lab, University of Zürich, Switzerland (50%)</p>
</div>
<!-- End entry 1-->

<!-- Sub Entry1.1: SR-SAVI-->
<!-- Circle-->
<div class="hover-circle" style="position: absolute; top: 225px; left: 295px; width: 12px; height: 12px; border: 2px solid #fff6f5; border-radius: 50%;" onclick="toggleInfo('info2')"></div>

<!-- Hover Text box -->
<div id="info2" style="position: absolute; top: 225px; left: 80px; width: 200px; padding: 10px; background-color: rgba(255, 255, 255, 0.9); color: #333; font-size: 16px; font-family: 'Crimson Pro', sans-serif; border: 1px solid #fff6f5; border-radius: 5px; display: none;">
  <p>I was one of the main organizers of the 2-day international meeting focused on the integration of automation and AI in systematic reviews and meta-analyses, the translational research bridging animal studies to human applications and policy implementation. More info on the <a href="https://marianna-rosso-uzh.github.io/SRSAVI//" target="_blank">website</a>, which I created</p>
</div>

<!-- Text -->
<div style="position: absolute; top: 218px; left: 330px; color: #fff6f5; line-height: 1.1;">
  <p style="margin: 0; font-family: 'Archivo Narrow', sans-serif; font-size: 18px;">SR-SAVI Conference (10.24)</p>
  <p style="margin: 0; font-family: 'Crimson Pro', serif; font-size: 15px;">Organizer and manager</p>
</div>

<!-- End subentry 1.1-->

<!-- Sub subentry 1.2: Bergen-->
<!-- Circle-->
<div class="hover-circle" style="position: absolute; top: 305px; left: 295px; width: 12px; height: 12px; border: 2px solid #fff6f5; border-radius: 50%;" onclick="toggleInfo('info3')"></div>

<!-- Hover Text box -->
<div id="info3" style="position: absolute; top: 305px; left: 80px; width: 200px; padding: 10px; background-color: rgba(255, 255, 255, 0.9); color: #333; font-size: 16px; font-family: 'Crimson Pro', sans-serif; border: 1px solid #fff6f5; border-radius: 5px; display: none;">
  <p>Details</p>
</div>

<!-- Text -->
<div style="position: absolute; top: 298px; left: 330px; color: #fff6f5; line-height: 1.1;">
 <p style="margin: 0; font-family: 'Archivo Narrow', sans-serif; font-size: 18px;">Summer School on Systematic Reviews of Animal Studies (8.24)</p>
  <p style="margin: 0; font-family: 'Crimson Pro', serif; font-size: 15px;">in collaboration with Norecopa, Bergen, Norway, organizer and lecturer</p>
</div>

<!-- End subentry 1.2-->

<!-- Sub subentry 1.3: Research-->
<!-- Circle-->
<div class="hover-circle" style="position: absolute; top: 385px; left: 295px; width: 12px; height: 12px; border: 2px solid #fff6f5; border-radius: 50%;" onclick="toggleInfo('info4')"></div>

<!-- Hover Text box -->
<div id="info4" style="position: absolute; top: 385px; left: 80px; width: 200px; padding: 10px; background-color: rgba(255, 255, 255, 0.9); color: #333; font-size: 16px; font-family: 'Crimson Pro', sans-serif; border: 1px solid #fff6f5; border-radius: 5px; display: none;">
  <p>Details</p>
</div>

<!-- Text -->
<div style="position: absolute; top: 378px; left: 330px; color: #fff6f5; line-height: 1.1;">
 <p style="margin: 0; font-family: 'Archivo Narrow', sans-serif; font-size: 18px;">Research focus (23-24)</p>
  <p style="margin: 0; font-family: 'Crimson Pro', serif; font-size: 15px;">.The role of systematic reviews in informing animal welfare policies in the EU</p>
  <p style="margin: 0; font-family: 'Crimson Pro', serif; font-size: 15px;">.Surveying Swiss researchers on the awereness and use of systematic reviews in clinical and animal research</p>
</div>

<!-- End subentry 1.3-->

<!-- Sub subentry 1.4: Summer School-->
<!-- Circle-->
<div class="hover-circle" style="position: absolute; top: 475px; left: 295px; width: 12px; height: 12px; border: 2px solid #fff6f5; border-radius: 50%;" onclick="toggleInfo('info5')"></div>

<!-- Hover Text box -->
<div id="info5" style="position: absolute; top: 475px; left: 80px; width: 200px; padding: 10px; background-color: rgba(255, 255, 255, 0.9); color: #333; font-size: 16px; font-family: 'Crimson Pro', sans-serif; border: 1px solid #fff6f5; border-radius: 5px; display: none;">
  <p>Details</p>
</div>

<!-- Text -->
<div style="position: absolute; top: 468px; left: 330px; color: #fff6f5; line-height: 1.1;">
 <p style="margin: 0; font-family: 'Archivo Narrow', sans-serif; font-size: 18px;">Summer School on Systematic Reviews of Animal Studies (8.23)</p>
  <p style="margin: 0; font-family: 'Crimson Pro', serif; font-size: 15px;">University of Zürich, organizer and lecturer</p>
</div>

<!-- End subentry 1.4-->

<!-- Break between positions-->
<div style="width: 13px; height: 13px; background-color: #eb6864; border-radius: 50%; position: absolute; top: 535px; left: 295px;"></div>

<!-- Entry2: USZ-->
<!-- Circle-->
<div class="hover-circle" style="position: absolute; top: 575px; left: 292px; width: 18px; height: 18px; border: 2px solid #fff6f5; border-radius: 50%;" onclick="toggleInfo('info6')"></div>

<!-- Hover Text box -->
<div id="info6" style="position: absolute; top: 575px; left: 80px; width: 200px; padding: 10px; background-color: rgba(255, 255, 255, 0.9); color: #333; font-size: 16px; font-family: 'Crimson Pro', sans-serif; border: 1px solid #fff6f5; border-radius: 5px; display: none;">
  <p>Details</p>
</div>

<!-- Text -->
<div style="position: absolute; top: 568px; left: 330px; color: white;line-height: 1.1;">
  <p style="margin: 0; font-family: 'Archivo Narrow', sans-serif;font-size: 24px; ">More to come</p>
  <p style="margin: 0; font-family: 'Crimson Pro', serif;font-size: 19px; ">soon...</p>
</div>
<!-- End entry 1-->


<script>
  function toggleInfo(infoId, circleId) {
    var infoBox = document.getElementById(infoId);
    var circle = document.getElementById(circleId);

    // Check if the clicked info box is already open
    var isCurrentlyOpen = (infoBox.style.display === "block");

    // Close all open text boxes
    var openInfoBoxes = document.querySelectorAll('div[id^="info"]');
    var circles = document.querySelectorAll('.hover-circle');

    openInfoBoxes.forEach(function(box) {
      box.style.display = 'none';
    });

    // Remove 'clicked' class from all circles
    circles.forEach(function(circle) {
      circle.classList.remove('clicked');
    });

    // If the clicked text box is not open, open it
    if (!isCurrentlyOpen) {
      infoBox.style.display = "block";
      circle.classList.add('clicked');
    }
  }
</script>
